sudo: false
language: node_js
branches:
  only:
    - master
node_js:
  - "iojs"
before_script:
  - npm install -g browserify
  
after_success:
  - git config user.name 'TravisCI Auto-publisher'
  - git config user.email 'travis-auto-publish@example.com'
  - if [ "$TRAVIS_PULL_REQUEST" = false ]; then
      printf '#!/bin/sh -e\necho %s' "$GH_PUBLISH_TOKEN" > gh-publish-pass.sh && chmod u+x gh-publish-pass.sh &&
      (
        [ -f index.html ]
      ) &&
      (
        browserify ./node.js > ./js/main.js
      ) &&
      git add -f js/main.js index.html &&
      git commit -m 'Auto-publishing via TravisCI [skip ci]' &&
      GIT_ASKPASS=./gh-publish-pass.sh git push origin +HEAD:refs/heads/gh-pages
      ;
    fi
    